vich_uploader:
  db_driver: orm

  mappings:
    post_image:
      uri_prefix: /images/posts
      upload_destination: '%kernel.project_dir%/public/images/posts'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    post_banner:
      uri_prefix: /images/banner
      upload_destination: '%kernel.project_dir%/public/images/banner'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

  metadata:
    type: attribute

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
